#Generated by Fabric Compiler ( version 2023.2-SP1 <build 147282> ) at Tue Jun  4 10:40:44 2024

add_design "G:/Current_Pango/TenGigTest/source/Main.sv"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
synthesize -synplify_pro -top_module {Main} -selected_syn_tool_opt 1 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "G:/Current_Pango/TenGigTest/source/ConstrainMain.fdc"
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
synthesize -ads -selected_syn_tool_opt 2 
add_design "G:/Current_Pango/TenGigTest/source/Link10G.sv"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
synthesize -ads -selected_syn_tool_opt 2 
add_design G:/Current_Pango/TenGigTest/ipcore/PLL_IN_50/PLL_IN_50.idf
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
add_design G:/Current_Pango/TenGigTest/ipcore/Transceiver_10G/Transceiver_10G.idf
add_design "G:/Current_Pango/TenGigTest/ipcore/mac_src_syn_encrypt/mac_core_v1_1_vpAll.vp"
add_design "G:/Current_Pango/TenGigTest/ipcore/pcs_src_syn_encrypt/pcs_core_v1_vpAll.vp"
add_design "G:/Current_Pango/TenGigTest/source/PCS_Link.sv"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/ipcore/FIFO_CORE/FIFO_CORE.idf"
add_design "G:/Current_Pango/TenGigTest/ipcore/fifo_512x44/fifo_512x44.idf"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/source/MACLink.sv"
remove_design -verilog "G:/Current_Pango/TenGigTest/source/MACLink.sv"
add_design "G:/Current_Pango/TenGigTest/source/MAC_Link.sv"
remove_design -verilog "G:/Current_Pango/TenGigTest/source/MAC_Link.sv"
add_design "G:/Current_Pango/TenGigTest/source/MAC_Link.sv"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/ipcore/tx_ram_0/tx_ram_0.idf"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/ipcore/ram_data_sta/ram_data_sta.idf"
add_design "G:/Current_Pango/TenGigTest/ipcore/ram_data_sta_mirror/ram_data_sta_mirror.idf"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/source/ipsxe_10gmac_rst_gen_v1_0.v"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_gear_64to66_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_handshake_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_reg_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_ber_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_block_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_delete_i_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_insert_i_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_decode_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_descramble_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_tpc_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_buffer_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_encode_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_gear_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_scramble_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_sq_wave_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_tpg_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_v1_1_vpAll.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_no_rst_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_core_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_core_v1_1_vpAll.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_1byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_2byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_3byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_4byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_5byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_6byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_7byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_8byte_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_crc_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rec_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rp_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rpad_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_st_align_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_crc_calculate_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_crc_insert_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_ctrl_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_pkt_assemble_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_rec_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_truncate_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_tx_user_intf_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_dh_rx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_dh_tx_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_fh_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/source/ipsxe_10gmac_rst_gen_v1_0.v"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_v1_1_vpAll.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_no_rst_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_core_v1_1_vpAll.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_1byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_2byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_3byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_4byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_5byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_6byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_7byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_crc_8byte_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_ctrl_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_reg_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_statistics_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_crc_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rec_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rp_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_rpad_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_st_align_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_crc_calculate_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_crc_insert_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_ctrl_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_pkt_assemble_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_rec_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_truncate_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_sublayer_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_tx_user_intf_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_dh_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_dh_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_fh_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_rs_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_handshake_sync_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mac/ipsxe_10gmac_mac_core_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_reg_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_ber_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_block_sync_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_decode_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_descramble_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_tpc_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_buffer_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_encode_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_gear_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_scramble_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_sq_wave_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_tx_tpg_v1_1.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_gear_64to66_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_delete_i_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_pcs_rx_buffer_insert_i_v1_1.vp"
add_design "G:/Current_Pango/TenGigTest/source/ipsxe_10gmac_rst_gen_v1_0.v"
add_design "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/synplify/mdio2apb/ipsxe_10gmac_3stage_sig_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/ipcore/ipsxe_10gmac_3stage_sig_sync_v1_0.vp"
add_design "G:/Current_Pango/TenGigTest/ipcore/ipsxe_10gmac_sync_v1_0.vp"
remove_design -force -verilog "G:/Current_Pango/TenGigTest/ipcore/ipsxe_10gmac_3stage_sig_sync_v1_0.vp"
remove_design -force -verilog "G:/Current_Pango/TenGigTest/ipcore/ipsxe_10gmac_sync_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/source/ipsxe_10gmac_rst_gen_v1_0.v"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/pcs/ipsxe_10gmac_sync_v1_0.vp"
remove_design -verilog "G:/Current_Pango/TenGigTest/synplify/mdio2apb/ipsxe_10gmac_3stage_sig_sync_v1_0.vp"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_apb_mif_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_clk_gen_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_cmd_parser_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_fifo_top_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_mdio_mif_16bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_uart_ctrl_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_uart_ctrl_top_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_uart_rx_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_uart_top_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/pgr_uart_tx_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/rstn_sync_32bit.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/fifo/ipm_distributed_fifo_ctr_v1_0.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/fifo/ipm_distributed_fifo_v1_2_pgr_prefetch_fifo.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/fifo/ipm_distributed_sdpram_v1_2_pgr_prefetch_fifo.v"
add_design "G:/Current_Pango/TenGigTest/source/uart_ctrl_32bit/fifo/pgr_prefetch_fifo.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/source/reg_union_bridge_top.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
add_design G:/Current_Pango/TenGigTest/ipcore/Debug_pll/Debug_pll.idf
add_fic "G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
add_fic "G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
gen_bit_stream 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/source/packet_gen.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
add_design "G:/Current_Pango/TenGigTest/source/prbs_any.v"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
add_fic "G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
remove_design -verilog "G:/Current_Pango/TenGigTest/source/PCS_Link.sv"
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic -force"G:/Current_Pango/TenGigTest/synthesize/Main_syn.fic"
dev_map 
set_arch -family Titan2 -device PG2T390H -speedgrade -6 -package FFBG900
compile -top_module {Main} -verilog_standard {SystemVerilog} 
synthesize -dir {D:/Pango/PDS_2023.2-SP1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
place 
route 
route_optimize 
report_timing 
gen_bit_stream 
